export const FETCH_DATA_REQUEST="FETCH_DATA_REQUEST"
export const FETCH_DATA_SUCCESS="FETCH_DATA_SUCCESS"
export const FETCH_DATA_FAILURE="FETCH_DATA_FAILURE"

export const SINGLE_PRODUCT_REQUEST="SINGLE_PRODUCT_REQUEST"
export const SINGLE_PRODUCT_SUCCESS="SINGLE_PRODUCT_SUCCESS"
export const SINGLE_PRODUCT_FAILURE="SINGLE_PRODUCT_FAILURE"

export const ADD_PRODUCT_CART_REQUEST="ADD_PRODUCT_CART_REQUEST"
export const ADD_PRODUCT_CART_SUCCESS="ADD_PRODUCT_CART_SUCCESS="
export const ADD_PRODUCT_CART_FAILURE="ADD_PRODUCT_CART_FAILURE"

export const FETCH_CART_REQUEST="FETCH_CART_REQUEST";
export const FETCH_CART_SUCCESS="FETCH_CART_SUCCESS";
export const FETCH_CART_FAILURE="FETCH_CART_FAILURE";

export const REMOVE_PRODUCT_CART_REQUEST="REMOVE_CART_REQUEST"
export const REMOVE_PRODUCT_CART_SUCCESS="REMOVE_CART_SUCCESS"
export const REMOVE_PRODUCT_CART_FAILURE="REMOVE_CART_FAILURE"